# base
avatar: imgs/avatar.png
index_text: "Lyusha Hexo Theme"
description: "A simple, elegant and focused card style Hexo theme"
language: zh-CN
footer_author_link: https://github.com/liuhq

# links
# https://simpleicons.org/
links:
    - name: email
      url: hora.liu@outlook.com
    - name: github
      url: https://github.com/liuhq
    - name: twitter
      url: https://twitter.com
    - name: bilibili
      url: https://space.bilibili.com
    # - name: instagram
    #   url:
    # - name: telegram
    #   url:
    # - name: zhihu
    #   url:
    # - name: sinaweibo
    #   url:
    ## other social links
    # - name:
    #   url:
    #   icon:

# about the "latest" mark
post_latest: true

# path of posts collection folder and posts list page
articles_folder: ""
