# 基础配置
avatar: https://api.prodless.com/avatar.png
index_text: 'Lyusha Hexo Theme'
description: 'A simple, elegant and focused card style Hexo theme'
language: zh-CN
footer_author_link: https://github.com/Qyir/

# links
# https://simpleicons.org/
links:
  - name: email
    url: voyoaugi@gmail.com
  - name: github
    url: https://github.com/Qyir/
  - name: twitter
    url: https://twitter.com/QoQyir
  - name: bilibili
    url: https://space.bilibili.com/89553968
  # - name: instagram
  #   url:
  # - name: telegram
  #   url:
  # - name: zhihu
  #   url:
  # - name: sinaweibo
  #   url:
  # - name:
  #   url:
  #   icon:

# 文章的 tip “最新”显示
post_latest: true

# post集合和次首页（home 页）路径/文件夹
articles_folder: ''